### PR TITLE
Delete empty file doc/keychart.

### PR DESCRIPTION
**Pull request by peterjc**
I'm hoping the empty file didn't actually do anything useful, because removing it ought to help building jove on (some) Windows setups.

Apparently the NTFS filesystem does not like filenames ending with a dot, quoting https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations

> The Win32 API strips trailing period (full-stop), and leading and trailing space
> characters from filenames, except when UNC paths are used

I believe this is breaking my effort to build Windows binaries for jove in conda-forge https://github.com/conda-forge/jove-feedstock/pull/12

### CODE REVIEW

**Comment by markmoraes** [comment]
Seems ok to me to get rid of that file -- the only reference to keychart.$TERM is in the jove.rc.$TERM files, so by definition, $TERM must be defined if I'm following the maze of *.rc right, and I am, um, skeptical if there's much use of either non-vt1xx terminal emulators or the keychart macro anymore)

**Comment by peterjc** [comment]
Fingers crossed - I'll retry with the next jove 4.17.x release. Thank you!

**Comment by peterjc** [comment]
Confirming removing this unusually named file did solve the problem breaking my conda-forge build (although it now fails later on - see https://github.com/conda-forge/jove-feedstock/pull/12 - I may open a fresh issue about that). Thank you.

**Comment by markmoraes** [comment]
`Makefile.msc` was intended for the `nmake` that ships with Visual C (and I recall testing it in Visual Studio a few years ago, but then whatever free license I had expired, and it's so much easier for me to test with mingw cross compile anyway, so that's what I switched to).  I cross-compile with `JMAKE_UNAME=i686-w64-mingw32 ./jmake.sh` which sets up some environment variables for convenience.

Is conda using a mingw/GNUish `make`?  `gcc`?

If so, something like 
```
make CC=i686-w64-mingw32-gcc SYSDEFS=-DMINGW OPTFLAGS=-g -Os -Wall -Werror -pedantic LDLIBS=-lcomdlg32 LDFLAGS= DESTDIR=/none/ JOVEHOME= JBINDIR= JSHAREDIR=doc JLIBDIR= XEXT=.exe WINDRES=i686-w64-mingw32-windres EXTRAOBJS=win32.o ICON=jjove.coff clobber all
```
might work -- you may need to replace the WINDRES invocation to whatever will run the relevant resource compiler, and similarly deal with the ICON.

**Pull request merged**
